{% set version = "3.0.1" %}

package:
  name: dunovo
  version: {{ version }}

source:
  url: https://github.com/galaxyproject/dunovo/archive/v{{ version }}.tar.gz
  sha256: 0f399a424503d4ea1587eafd0874335997695590039b2513a34da79a8eed686f

build:
  number: 0
  skip: True  # [py2k or osx]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - wget
  host:
    - python
    - pip
  run:
    - python
    - mafft 7.221
    - bowtie >=1.2.1.1
    - networkx >=2.4
    - paste
    - gawk

test:
  commands:
    - 'correct.py --version > /dev/null'
    - 'align-families.py --version > /dev/null'
    - 'make-consensi.py --version > /dev/null'
    - 'precheck.py --help > /dev/null'
    - 'trimmer.py --help > /dev/null'
  imports:
    - networkx

about:
  home: https://github.com/galaxyproject/dunovo
  license: GPLv2
  license_file: LICENSE.txt
  summary: "Du Novo: A pipeline for processing duplex sequencing data."
